In [2]:
import pandas as pd
df=pd.read_csv('/Users/lambardaar/Downloads/skill-practice-lab/NLP/IMDB Dataset.csv')
df

                                                  review sentiment
0      One of the other reviewers has mentioned that ...  positive
1      A wonderful little production. <br /><br />The...  positive
2      I thought this was a wonderful way to spend ti...  positive
3      Basically there's a family where a little boy ...  negative
4      Petter Mattei's "Love in the Time of Money" is...  positive
...                                                  ...       ...
49995  I thought this movie did a down right good job...  positive
49996  Bad plot, bad dialogue, bad acting, idiotic di...  negative
49997  I am a Catholic taught in parochial elementary...  negative
49998  I'm going to have to disagree with the previou...  negative
49999  No one expects the Star Trek movies to be high...  negative

[50000 rows x 2 columns]

In [ ]:
# text preprocessing
df['review']=df['review'].str.lower()

import re
def html_rem(data):
    p=re.compile('<.*?>')
    return p.sub('',data)

df['review']=df['review'].apply(html_rem)

# remove punctuation
import string
df['review'] = df['review'].str.replace(f"[{string.punctuation}]", "", regex=True)

#remove extra space
df['text'] = df['text'].str.strip()

                                                  review sentiment
0      one of the other reviewers has mentioned that ...  positive
1      a wonderful little production. the filming tec...  positive
2      i thought this was a wonderful way to spend ti...  positive
3      basically there's a family where a little boy ...  negative
4      petter mattei's "love in the time of money" is...  positive
...                                                  ...       ...
49995  i thought this movie did a down right good job...  positive
49996  bad plot, bad dialogue, bad acting, idiotic di...  negative
49997  i am a catholic taught in parochial elementary...  negative
49998  i'm going to have to disagree with the previou...  negative
49999  no one expects the star trek movies to be high...  negative

[50000 rows x 2 columns]

In [ ]:
#corpus count
ans=0
for i in df['review']:
    ans+=len(i.split())
print(ans)

#vocalolary count
vocab = set(" ".join(df['review']).split())#make each row to a single string and then find length 
print(len(vocab))

11355604

In [14]:
#bag of words
from sklearn.feature_extraction.text import CountVectorizer
import numpy as np
cv=CountVectorizer()
v=cv.fit_transform(df['review'])
print(v[0].toarray())

[[0 0 0 ... 0 0 0]]